---
title: "Simulation-based Inference for Epidemiological Dynamics"
author: "Aaron A. King, Edward L. Ionides, Kidus Asfaw"
output: html_document
bibliography: sbied.bib
csl: jss.csl

---

## Module description

This module introduces statistical inference techniques and computational methods for dynamic models of epidemiological systems.
The course will explore deterministic and stochastic formulations of epidemiological dynamics and develop inference methods appropriate for a range of models.
Special emphasis will be on exact and approximate likelihood as the key elements in parameter estimation, hypothesis testing, and model selection. Specifically, the course will cover sequential Monte Carlo and synthetic likelihood techniques.
Students will learn to implement these in R to carry out maximum likelihood and Bayesian inference. Knowledge of the material in Module 1 is assumed.
Students new to R should complete a [tutorial](https://kingaa.github.io/R_Tutorial/) before the module.

## Course objectives

1. to introduce partially observed Markov process (POMP) models as tools for scientific investigation and public health policy
1. to give students the ability to formulate POMP models of their own
1. to teach efficient approaches for performing scientific inference using POMP models
1. to familiarize students with the **pomp** package
1. to give students opportunities to work with such inference methods
1. to provide documented examples for student re-use

----------------------

## Lessons

| &nbsp; | &nbsp; | &nbsp; | &nbsp; | &nbsp; |
|:----------------------------------------|:---:|:---:|:---:|:--:|
| **0. Instructions for preparing your laptop for the course exercises** | &nbsp; | [Page (HTML)](./prep/index.html) | &nbsp; | &nbsp; |
| [**1. Introduction: What is "Simulation-based Inference for Epidemiological Dynamics"?**](./intro/) | <a href="https://www.youtube.com/playlist?list=PLluGwj6FGt2Sns4ChQCJy6T7Nz00r5zXV" target="_blank">Lecture</a> | [Slides (PDF)](./intro/slides.pdf) | [Notes (PDF)](./intro/notes.pdf) |
| [**2. Simulation of stochastic dynamic models.**](./stochsim/) | Lecture | [Slides (PDF)](./stochsim/slides.pdf) | [Notes (PDF)](./stochsim/notes.pdf) | [Script (**R**)](http://raw.githubusercontent.com/kingaa/sbied/master/stochsim/main.R) |
| [**3. Likelihood for POMPs: theory and practice.**](./pfilter/) | Lecture | [Slides (PDF)](./pfilter/slides.pdf) | [Notes (PDF)](./pfilter/notes.pdf) | [Script (**R**)](http://raw.githubusercontent.com/kingaa/sbied/master/pfilter/main.R) |
| [**4. Iterated filtering: theory and practice.**](./mif/) | Lecture | [Slides (PDF)](./mif/slides.pdf) | [Notes (PDF)](./mif/notes.pdf) | [Script (**R**)](http://raw.githubusercontent.com/kingaa/sbied/master/mif/main.R) |
| [**5. Case study: recurrent measles dynamics revealed in long time series.**](./mif/) | Lecture | [Slides (PDF)](./measles/slides.pdf) | [Notes (PDF)](./measles/notes.pdf) | [Script (**R**)](http://raw.githubusercontent.com/kingaa/sbied/master/measles/main.R) |
| [**6. Case study: polio.**](./polio/) | <a href="https://www.youtube.com/playlist?list=PLluGwj6FGt2RuunOUW3MqFcrcgydWhgS8" target="_blank">Lecture</a> | [Slides (PDF)](./polio/slides.pdf) | [Notes (PDF)](./polio/notes.pdf) | [Script (**R**)](http://raw.githubusercontent.com/kingaa/sbied/master/polio/main.R) |
| [**7. Case study: Ebola, model diagnostics, and forecasting.**](./ebola/) | <a href="https://www.youtube.com/playlist?list=PLluGwj6FGt2R5iGmfPTO9slNQyfJlAV4Z" target="_blank">Lecture</a> | [Slides (PDF)](./ebola/slides.pdf) | [Notes (PDF)](./ebola/notes.pdf) | [Script (**R**)](http://raw.githubusercontent.com/kingaa/sbied/master/ebola/codes.R) |
| [**8. Case study: sexual contacts panel data.**](./contacts/) | <a href="https://www.youtube.com/playlist?list=PLluGwj6FGt2SzWigyV88kFPZ2OEW18pQS" target="_blank">Lecture</a> | [Slides (PDF)](./contacts/slides.pdf) | [Notes (PDF)](./contacts/notes.pdf) | [Script (**R**)](http://raw.githubusercontent.com/kingaa/sbied/master/contacts/main.R) |

------------------------------------

[Acknowledgements](./acknowledge.html)  
[Source code for these notes](http://github.com/kingaa/sbied/)  
[**pomp** homepage](https://kingaa.github.io/pomp/)  

----------------------
