#' ---
#' title: "Simulation of stochastic dynamic models: Optional exercises"
#' author: "Carles Bretó"
#' output:
#'   html_document:
#'     toc: no
#'     toc_depth: 4
#' bibliography: ../sbied.bib
#' csl: ../ecology.csl
#' ---
#' 
#' \newcommand\prob[1]{\mathbb{P}\big[{#1}\big]}
#' \newcommand\expect[1]{\mathbb{E}\big[{#1}\big]}
#' \newcommand\var[1]{\mathrm{Var}\left[{#1}\right]}
#' \newcommand\dist[2]{\mathrm{#1}\left(#2\right)}
#' \newcommand\dlta[1]{{\Delta}{#1}}
#' \newcommand\lik{\mathcal{L}}
#' \newcommand\loglik{\ell}
#' 
#' [Licensed under the Creative Commons Attribution-NonCommercial license](http://creativecommons.org/licenses/by-nc/4.0/).
#' Please share and remix noncommercially, mentioning its origin.  
#' ![CC-BY_NC](../graphics/cc-by-nc.png)
#' 
#' ## Optional Exercise: From Markov chain to ODE
#' 
#' The expected value of the random variables $\dlta{N}_{SI}(t) = N_{SI}(t+\delta)-N_{SI}(t)$, which take values on the finite set $\{0,\ldots,N\}$, is
#' $$
#' \begin{aligned}
#' \expect{\dlta{N}_{SI}(t) \,|\, S(t), I(t), R(t)} &= \sum_{x=0}^{N} x\prob{\dlta{N}_{SI}(t)=x} \\
#'  &= \prob{\dlta{N}_{SI}(t)=1 \,|\, S(t), I(t), R(t)} + o(\delta) \\
#'  &= \mu_{SI}(t)\,S(t)\,\delta + o(\delta)\\
#' \end{aligned}
#' $$
#' Taking the limit as $\delta\to 0$ gives back the original ODE rate
#' $$
#' \begin{aligned}
#' \lim_{\delta\to 0}\frac{\expect{\dlta{N}_{SI}(t) \,|\, S(t), I(t), R(t)}}{\delta} &= \lim_{\delta\to 0}\frac{\mu_{SI}(t)\,S(t)\,\delta}{\delta} + \lim_{\delta\to 0}\frac{o(\delta)}{\delta} = \mu_{SI}(t)\,S(t)
#' \\
#' \end{aligned}
#' $$
#' 
#' ## Optional Exercise: SDE version of the SIR model
#' 
#' The Euler-Maruyama method for an SDE representation of the closed-population SIR model results in the following equations
#' The so-called Euler-Maruyama approximation $\tilde X$ is generated by 
#' $$
#' \begin{aligned}
#' \tilde S(\tilde t_{k+1}) &= \tilde S(\tilde t_k) - \delta\,\mu_{SI}(t)\,\tilde S(\tilde t_k) + \sigma_{SI} \sqrt{\delta} \, Z_{SI} \\
#' \tilde I(\tilde t_{k+1}) &= \tilde I(\tilde t_k) - \delta\,\big(\mu_{SI}(t)\,\tilde S(\tilde t_k) - \mu_{IR}(t)\,\tilde I(\tilde t_k)\big) + \sigma_{IR} \sqrt{\delta} \, Z_{IR}\\
#' \tilde R(\tilde t_{k+1}) &= N - \tilde S(\tilde t_{k+1}) - \tilde I(\tilde t_{k+1}) 
#' \end{aligned}
#' $$
#' where $Z_{SI}$ and $Z_{IR}$ are independent standard normal random variables. The values of $\sigma_{SI}$ and $\sigma_{IR}$ can be chosen to reflect different sources of stochasticity. For example, setting them to the square root of the preceeding term, e.g., $\sigma_{SI}=\sqrt{\mu_{SI}(t)\,\tilde S(\tilde t_k) - \mu_{IR}(t)\,\tilde I(\tilde t_k)}$, reflects demographic stochasticity.
#' 
#' Difficulties that might arise with non-negativity constraints can occurr when the left hand side of the equations become negative, e.g., because of large intervals $\delta$, high rates $\mu$, large values of the normal random variables $Z$ or because of large values of $\tilde S(\tilde t_{k+1}) + \tilde I(\tilde t_{k+1})$. One practical way to deal with this issue is to truncate negative numbers to zero.
#' 
#' ----------------------------
#' 
#' ## [Back to Stochastic Simulation lesson](./stochsim.html)
#' 
#' ----------------------------
#' 
#' ## References
