---
title: |
  | Worked solution to exercise 3.3:
  | Precision and accuracy of particle-filter likelihood estimates
author: "Aaron A. King"
output:
  html_document:
    toc: no
    toc_depth: 4
    includes:
      after_body:
      - ../_includes/supp_bottom.html
      - ../_includes/license.html
bibliography: ../sbied.bib
csl: ../jss.csl
params:
  prefix: llest
---

--------------------

[**R** codes for this document](./loglikest.R)  

```{r knitr-opts,include=FALSE,purl=FALSE}
source("../setup.R", local = knitr::knit_global())
```
```{r prelims,purl=TRUE,cache=FALSE}
library(tidyverse)
library(pomp)
set.seed(1221234211)
```

Model implementation

```{r model-construct}
source("https://kingaa.github.io/sbied/pfilter/model.R")
```

Testing the particle filter:

```{r test}
measSIR %>% pfilter(Np=1000) -> pf
logLik(pf)
```

Now, we evaluate the dependence of log likelihood estimates 
on particle size and number of independent filters.
We first set up a parallel computation environment.

```{r parallel_setup,eval=FALSE,purl=FALSE}
library(foreach)
library(doParallel)
library(doRNG)
registerDoParallel()
registerDoRNG(594717807L)
```
```{r cluster,purl=TRUE,eval=FALSE,include=FALSE}
if (file.exists("CLUSTER.R")) {
  source("CLUSTER.R")
}
library(doRNG)
registerDoRNG(594717807L)
```

```{r comps,eval=FALSE,purl=FALSE}
expand_grid(
  rep=1:1000,
  Np=c(1000,10000,100000)
) -> design

foreach (p=iter(design,"row"),
         .inorder=FALSE, .combine=rbind) %dopar%
  {
    library(pomp)
    measSIR %>% pfilter(Np=p$Np) -> pf
    cbind(p,loglik=logLik(pf))
  } -> lls
```
```{r comps-eval,include=FALSE}
bake(file="loglikest-pfilter.rds",{
  <<cluster>>
  <<comps>> 
  registerDoSEQ()
  lls
}) -> lls
```

Violin plots display the distributions.

```{r plots}
expand_grid(
  nfilt=c(10,100,1000),
  lls
) %>%
  filter(rep<=nfilt) %>%
  ggplot(aes(x=Np,y=loglik,fill=ordered(nfilt),
             group=interaction(nfilt,Np)))+
  geom_violin(draw_quantiles=c(0.1,0.5,0.9),alpha=0.7)+
  scale_x_log10(breaks=unique(lls$Np))+
  labs(fill="nfilt")
```
