default: index.html slides.pdf notes.pdf main.R \
bootstrap.html deterministic.html expense.html \
directSimulation.html directSimulation.R \
monteCarlo.pdf fisherSE.html \
loglikest.html loglikest.R \
pf-in-Nelder-Mead.html pf-in-Nelder-Mead.R \
basic_exercise_pfilter.html basic_exercise_pfilter.R \
Q_slice.html bake.html \
quiz.pdf quiz_soln.pdf

.INTERMEDIATE: monteCarlo.tex

include ../rules.mk
