\documentclass{article}
\usepackage{beamerarticle}
\usepackage[top=1in,left=1in,footskip=1in]{geometry}
\usepackage[unicode=true,bookmarksnumbered=false,bookmarksopen=false,breaklinks=true,backref=section,colorlinks=true,urlcolor=blue,citecolor=black,linkcolor=blue,filecolor=blue]{hyperref}
\setjobnamebeamerversion{slides}
\input{beamer}
\input{main}

<<knitr_opts,include=FALSE,cache=FALSE,purl=FALSE>>=
source("../_includes/setup.R", local = knitr::knit_global())
@

