---
title: "Worked solution to 'Pfiltering a panelPomp'"
output:
  html_document:
    toc: yes
    toc_depth: 3
bibliography: ../sbied.bib
csl: ../ecology.csl
---

```{r knitr-opts,include=FALSE,cache=FALSE,purl=FALSE}
library(knitr)
prefix <- "contacts"
opts_chunk$set(
  progress=TRUE,
  prompt=FALSE,tidy=FALSE,highlight=TRUE,
  strip.white=TRUE,
  warning=FALSE,
  message=FALSE,
  error=FALSE,
  echo=TRUE,
  cache=TRUE,
  cache_extra=rand_seed,
  results='markup',
  fig.show='asis',
  size='small',
  fig.lp="fig:",
  fig.path=paste0("figure/",prefix,"-"),
  cache.path=paste0("cache/",prefix,"-"),
  fig.pos="h!",
  fig.align='center',
  fig.height=4,fig.width=6.83,
  dpi=300,
  dev='png',
  dev.args=list(bg='transparent')
)

```

```{r echo=F}
library(panelPomp)
```

* Since a PanelPOMP is a collection of independent POMP models, they can each be filtered separately.

* The `pfilter` method for class `panelPomp` does exactly this, after extracting the parameter vector for each unit from the shared and unit-specific parameters belonging to the `panelPomp` object.

```{r}
contacts <- panelPompExample(pancon)
pf <- pfilter(contacts,Np=100)
class(pf)
class(unitobjects(pf)[[1]])
```

