# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:

name: install-test

jobs:
  install-test:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-22.04, r: 'release'}
          - {os: ubuntu-20.04, r: '4.2.0'}
          - {os: macOS-11,     r: 'release'}
          - {os: macOS-12,     r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: '4.2.0'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_LIBS_USER: ${{ github.workspace }}/R

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: r-lib/actions/setup-r@v2.3.1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Run tests
        run: |
          sink("test.out")
          update.packages(lib.loc=Sys.getenv("R_LIBS_USER"))
          source("https://kingaa.github.io/sbied/prep/packages.R")
          source("https://kingaa.github.io/scripts/pompTest.R")
          source("https://kingaa.github.io/scripts/hello.R",echo=TRUE)
          source("https://kingaa.github.io/sbied/contacts/install.R",echo=TRUE)
          source("https://kingaa.github.io/scripts/diagnostics.R",echo=TRUE)
          sink()
        shell: Rscript {0}
      
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ matrix.config.os }}-${{ matrix.config.r }}-results
          path: ${{ github.workspace }}/test.out
